export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_INCOME = 'ADD_INCOME';
export const UPDATE_INCOME = 'UPDATE_INCOME';
export const DELETE_INCOME = 'DELETE_INCOME';
export const ADD_SAVINGS = 'ADD_SAVINGS';
export const UPDATE_SAVINGS = 'UPDATE_SAVINGS';
export const DELETE_SAVINGS = 'DELETE_SAVINGS';
export const ADD_BILLS = 'ADD_BILLS';
export const ADD_NEXT_PAY_DATE = 'ADD_NEXT_PAY_DATE';
export const GET_BALANCE = 'GET_BALANCE';
export const SORT_BY_INCOME_ASCENDING = "SORT_BY_INCOME_ASCENDING";
export const SORT_BY_INCOME_DESCENDING = "SORT_BY_INCOME_DESCENDING";
export const SORT_BY_DATE_ASCENDING = "SORT_BY_DATE_ASCENDING";
export const SORT_BY_DATE_DESCENDING = "SORT_BY_DATE_DESCENDING";
export const SORT_BY_SAVINGS_AMOUNT_ASCENDING = "SORT_BY_INCOME_ASCENDING";
export const SORT_BY_SAVINGS_AMOUNT_DESCENDING = "SORT_BY_INCOME_DESCENDING";
export const SORT_BY_SAVINGS_DESCRIPTION_ASCENDING = "SORT_BY_SAVINGS_DESCRIPTION_ASCENDING";
export const SORT_BY_SAVINGS_DESCRIPTION_DESCENDING = "SORT_BY_SAVINGS_DESCRIPTION_DESCENDING";




